steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/excel-addin-backend-repo/excel-addin-backend:$SHORT_SHA'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/excel-addin-backend-repo/excel-addin-backend:$SHORT_SHA'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    timeout: '300s' # Add a 5-minute timeout for the deployment step
    args:
      - 'run'
      - 'deploy'
      - 'excel-addin-backend'
      - '--image=asia-south1-docker.pkg.dev/${PROJECT_ID}/excel-addin-backend-repo/excel-addin-backend:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--health-check-path=/healthz'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=plus-percent:asia-south1:excel-addin-db'
      - '--set-env-vars=DB_NAME=Price data'
      - '--set-env-vars=DB_USER=sqlserver'
      - '--update-secrets=DB_PASS=excel-db-pass:latest'

images:
  - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/excel-addin-backend-repo/excel-addin-backend:$SHORT_SHA'
